### ISSUE TITLE
Add some :heart: to the README.md

### ISSUE THREAD

**Issue by jglovier** [alysonla/hubber-memory-game#4]
I would suggest adding some :heart: to the README file so people who want to download and run the game know how, and so people who want to contribute know your preferred workflow (dat GitHub flow).

Also, I'll be happy to address said README issues in my PR with the design love coming up. :wink:

**Comment by alysonla** [comment]
Finally updated this today! ✨ Still waiting on that PR but I'd also love to pair if you're up for it! 😊

**Comment by jglovier** [comment]
> Still waiting on that PR but I'd also love to pair if you're up for it! :blush:

Yes!! Let's absolutely do that. My momentum got stuck last time when I couldn't get Team setup locally, but if we schedule a pairing session that would force me to get it done, plus I could show you how I approach a design process like this.

When is a good time for us to do pair?

**Comment by alysonla** [comment]
@jglovier omg that would be amazing. :raised_hands: 

I'm actually in NYC for a conference the next few days (missed the hubber crew by a week!) so how about next week? I'm pretty flexible & can add a time to the :calendar:.

**Comment by jglovier** [comment]
@alysonla hey I got a great idea! How bout we do this in the office when I'm in town Nov 2-8? We can pair in :meat_on_bone: :stars: ?

**Comment by alysonla** [comment]
@jglovier yesss!
