### ISSUE TITLE
Update code to use GitHub's public API

### ISSUE THREAD

**Issue by alysonla** [alysonla/hubber-memory-game#5]
Would like to replace the json with github's public api to pull in all hubbers in the github organization. :sparkles:

**Comment by IonicaBizau** [comment]
@alysonla Can I do this? :smile_cat:

**Comment by alysonla** [comment]
@IonicaBizau omg that would be amazing. :bow:

**Comment by IonicaBizau** [comment]
@alysonla Addressed in #8. I know a trick to fetch the GitHub's private members too–even those that are _more private_ than [here](https://github.com/about/team). :laughing: But you asked about the public API, so I used it. :sparkle:

In fact, it uses public GitHub API requests and if it fails, it fallbacks to the json file which can be updated using `node build.js <token>` (make sure to pass a scopeless token if you only want to fetch the public members). :smile:
